name = "eduaneltarot"
compatibility_date = "2024-06-01"
[assets]
directory = "."
# Esto asegura que todo el contenido de esas carpetas se suba
include = ["assets/**/*", "data/**/*"]

[[kv_namespaces]]
binding = "HOROSCOPE_KV"
id = "5dea61df36b641f199aada56db691ca5"